version = 0.1
[default.deploy.parameters]
stack_name = "mmog"
resolve_s3 = true
s3_prefix = "mmog"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
parameter_overrides = "ConnectionsTableName=\"mmog-connections\" ObjectsTableName=\"mmog-objects\""
